repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.2.0
        hooks:
        -   id: check-ast
            language_version: python3.7
        -   id: check-byte-order-marker
            language_version: python3.7
        -   id: check-builtin-literals
            language_version: python3.7
        -   id: check-docstring-first
            language_version: python3.7
        -   id: check-json
            language_version: python3.7
        -   id: check-merge-conflict
            language_version: python3.7
        -   id: check-yaml
            language_version: python3.7
        -   id: debug-statements
            language_version: python3.7
        -   id: detect-private-key
            language_version: python3.7
        -   id: double-quote-string-fixer
            language_version: python3.7
        -   id: end-of-file-fixer
            language_version: python3.7
            types: [python]
        -   id: fix-encoding-pragma
            language_version: python3.7
        -   id: requirements-txt-fixer
            language_version: python3.7
        -   id: trailing-whitespace
            language_version: python3.7
    -   repo: https://github.com/pre-commit/mirrors-autopep8
        rev: v1.5.4
        hooks:
        -   id: autopep8
            language_version: python3.7
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.782
        hooks:
        -   id: mypy
            language_version: python3.7
    -   repo: https://github.com/asottile/reorder_python_imports
        rev: v2.3.5
        hooks:
        -   id: reorder-python-imports
            language_version: python3.7
            args: [--py3-plus]